
spring.application.name=shopease

# Load the project-root .env file
spring.config.import=optional:file:.env[.properties]

# PostgreSQL
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Thymeleaf
spring.thymeleaf.cache=false

# Helpful during development
server.error.include-message=always